[package]
name = "rust_example"
version = "0.1.0"
authors = ["ggomagundan <pbs52@hanmail.net>"]

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"


[[bin]]
name = "fibonacci"
path = "src/fibonacci/main.rs"
